receivers:
  otlp:
    protocols:
      grpc:
      http:
        endpoint: ":4318"

exporters:
  debug:
  otlphttp/mackerel:
    endpoint: "https://otlp-vaxila.mackerelio.com"
    headers:
      Accept: "*/*"
      "Mackerel-Api-Key": ${env:MACKEREL_APIKEY}

processors:
  batch:
    send_batch_size: 5000
    send_batch_max_size: 5000

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, otlphttp/mackerel]
